### ISSUE TITLE
4.10.1146.0 -> 1.4.9.1088

### ISSUE THREAD

**Issue by matthuisman** [glennguy/script.module.drmhelper#1]
Hi guys,

You might want to update your links to point to the 1.4.9.1088 I have just uploaded.
https://github.com/matthuisman/decryptmodules/raw/master/widevine/1.4.9.1088-linux-armv7.so

4.10.1146.0 has issues with Netflix add-on (user reported).

Thanks,

Matt

**Comment by glennguy** [comment]
Awesome, thanks for the heads up Matt!
